# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEm7fjUT3akNaLhsJNbRbTeAolcst3G2
"""

import streamlit as st
import requests

st.title("🎓 Student Marks Predictor")

hours = st.number_input("Enter study hours")

if st.button("Predict"):

    response = requests.post(
        "http://127.0.0.1:8000/predict",
        json={"hours": hours}
    )

    result = response.json()

    st.success(f"Predicted Marks: {result['marks']}")

