# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5ivnnQ5QVUBoE3tq02qXH_JPhFevK17
"""

from fastapi import FastAPI
import pickle
import numpy as np

app = FastAPI()

# load model
model = pickle.load(open("model.pkl", "rb"))

@app.get("/")
def home():
    return {"message": "API is working"}

@app.post("/predict")
def predict(data: dict):
    hours = data["hours"]

    arr = np.array([[hours]])
    prediction = model.predict(arr)

    return {"marks": float(prediction[0])}

